import { Effect, Result } from "effect";
import { fetchChromium, fetchOmaha } from "./chromium.ts"; 
import { fetchMozilla, fetchAMO } from "./mozilla.ts";
import { Addon, fetch } from "./util.ts";
import { fetchGitHub } from "./github.ts";

const addon = (id: string) =>
  Effect.map((r: Result.Result<Record<string, Result.Result<Addon, Error>>, Error>) =>
    Result.flatMap(r, (r) => r[id])
  );

export default {
  chromium: {
    "_1password": fetchOmaha("aeblfdkhhhdcdjpifhhbdiojplfjncoa"),
    "anubis-bypass": fetchChromium("https://webextensions.andre4ik3.dev/updates.xml").pipe(addon("hbocpnemmimnkcddekhpiogjigmjnemb")),
    "betterttv": fetchOmaha("ajopnjidmegmdimjlfnijceegpefgped"),
    "bitwarden": fetchOmaha("nngceckbapebfimnlniiiahkandclblb"),
    "bypass-paywalls-clean": fetchChromium("https://gitflic.ru/project/magnolia1234/bpc_updates/blob/raw?file=updates.xml").pipe(addon("lkbebcjgcmobigpeffafkodonchffocl")),
    "catppuccin-web-file-icons": fetchOmaha("lnjaiaapbakfhlbjenjkhffcdpoompki"),
    "consent-o-matic": fetchOmaha("mdjildafknihdffpkfmmpnpoiajfjnjd"),
    "consumer-rights-wiki": fetchOmaha("bppajinomefndbbmopljhbdfefnefdha"),
    "dark-reader": fetchOmaha("eimadpbcbfnmbkopoojfekhnkhdbieeh"),
    "decentraleyes": fetchOmaha("ldpochfccmkkmhdbclfhpagapcfdljkj"),
    "duckduckgo": fetchOmaha("bkdgflcldnnnapblkhphbgpggdiikppg"),
    "icloud-passwords": fetchOmaha("pejdijmoenmkgeppbflobdenhhabjlaj"),
    "jshelter": fetchOmaha("ammoloihpcbognfddfjcljgembpibcmb"),
    "justdeleteme": fetchOmaha("dlhckcablohllindinahbbpnfgblimoe"),
    "keepassxc-browser": fetchOmaha("oboonakemofpalcgghocfoadofidjkkk"),
    "languagetool": fetchOmaha("oldceeleldhonbafppcapldpdifcinji"),
    "libredirect": fetchChromium("https://raw.githubusercontent.com/libredirect/libredirect/master/src/updates/updates.xml").pipe(addon("oladmjdebphlnjjcnomfhhbfdldiimaf")),
    "noscript": fetchOmaha("doojmbjmlfjjnbmnoijecmcbfeoakpjm"),
    "obsidian-web-clipper": fetchOmaha("cnjifjpddelmedmihgijeibhnjfabmlf"),
    "plasma-integration": fetchOmaha("cimiefiiaegbelhefglklhhakcgmhkai"),
    "privacy-badger": fetchOmaha("pkehgijcmpdhfbdbbnkijodmdjhbjlgp"),
    "privacy-pass": fetchOmaha("ajhmfdgkijocedmfjonnpjfojldioehi"),
    "react-devtools": fetchOmaha("fmkadmapgofadopljbjfkapdkoienihi"),
    "redux-devtools": fetchOmaha("lmhkpmbekcpmknklioeibfkpmmfibljd"),
    "return-youtube-dislike": fetchOmaha("gebbhagfogifgggkldgodflihgfeippi"),
    "snowflake": fetchOmaha("mafpmfcccpbjnhfhjnllmmalhifmlcie"),
    "sponsorblock": fetchOmaha("mnjggcdmjocbbbhaepdhchncahnbgone"),
    "steamdb": fetchOmaha("kdbmhfkmnlmbkgbabkdealhhbfhlmmon"),
    "stylus": fetchOmaha("clngdbkpkpeebahjckkjfobafhncgmne"),
    "svelte-devtools": fetchOmaha("kfidecgcdjjfpeckbblhmfkhmlgecoff"),
    "tampermonkey": fetchOmaha("dhdgffkkebhmkfjojejmpbldmpobfkfo"),
    "ublock-origin": fetchChromium("https://raw.githubusercontent.com/imputnet/ublock-origin-crx/refs/heads/main/update.xml").pipe(addon("blockjmkbacgjkknlgpkjjiijinjdanf")),
    "ublock-origin-lite": fetchOmaha("ddkjiahejlhfcafbddmgiahcphecmpfh"),
    "unhook": fetchOmaha("khncfooichmfjbepaaaebmommgaepoid"),
    "user-agent-switcher": fetchOmaha("djflhoibgkdhkhhcedjiklpkjnoahfmg"),
    "video-download-helper": fetchOmaha("lmjnegcaeklhafolokijcfjliaokphfk"),
    "vimium": fetchOmaha("dbepggeogbaibhgnhhndojpepiihcmeb"),
    "violentmonkey": fetchOmaha("jinjaccalgkegednnccohejagnlnfdag"),
    "vuejs-devtools": fetchOmaha("nhdogjmejiglipccpnnnanhbledajbpd"),
    "web-archives": fetchOmaha("hkligngkgcpcolhcnkgccglchdafcnao"),
    "webrtc-network-limiter": fetchOmaha("npeicpdbkakmehahjeeohfdhnlpdklia"),
    "zotero-connector": fetchOmaha("ekhagklcjbdpajgpjgmbionohlpdbjgc"),
  },
  firefox: {
    "_1password": fetchAMO("firefox", "{d634138d-c276-4fc8-924b-40a0ea21d284}"),
    "adaptive-tab-bar-color": fetchAMO("firefox", "ATBC@EasonWong"),
    "anubis-bypass": fetchMozilla("https://webextensions.andre4ik3.dev/updates.json").pipe(addon("anubis-bypass@andre4ik3.dev")),
    "auto-tab-discard": fetchAMO("firefox", "{c2c003ee-bd69-42a2-b0e9-6f34222cb046}"),
    "betterttv": fetchAMO("firefox", "firefox@betterttv.net"),
    "bitwarden": fetchAMO("firefox", "{446900e4-71c2-419f-a6a7-df9c091e268b}"),
    "bypass-paywalls-clean": fetchMozilla("https://gitflic.ru/project/magnolia1234/bpc_updates/blob/raw?file=updates.json").pipe(addon("magnolia@12.34")),
    "bypass-paywalls-clean-limited-permissions": fetchMozilla("https://gitflic.ru/project/magnolia1234/bpc_updates/blob/raw?file=updates.json").pipe(addon("magnolia_limited_permissions@12.34")),
    "canvasblocker": fetchAMO("firefox", "CanvasBlocker@kkapsner.de"),
    "canvasblocker-beta": fetchMozilla("https://canvasblocker.kkapsner.de/versions/updates.json").pipe(addon("CanvasBlocker-Beta@kkapsner.de")),
    "catppuccin-web-file-icons": fetchAMO("firefox", "{bbb880ce-43c9-47ae-b746-c3e0096c5b76}"),
    "clearurls": fetchAMO("firefox", "{74145f27-f039-47ce-a470-a662b129930a}"),
    "consent-o-matic": fetchAMO("firefox", "gdpr@cavi.au.dk"),
    "consumer-rights-wiki": fetchAMO("firefox", "@crw-extension-firefox"),
    "copy-plaintext": fetchAMO("firefox", "copyplaintext@eros.man"),
    "dark-reader": fetchAMO("firefox", "addon@darkreader.org"),
    "decentraleyes": fetchAMO("firefox", "jid1-BoFifL9Vbdl2zQ@jetpack"),
    "duckduckgo": fetchAMO("firefox", "jid1-ZAdIEUB7XOzOJw@jetpack"),
    "foxyproxy": fetchAMO("firefox", "foxyproxy@eric.h.jung"),
    "icloud-passwords": fetchAMO("firefox", "password-manager-firefox-extension@apple.com"),
    "jshelter": fetchAMO("firefox", "jsr@javascriptrestrictor"),
    "justdeleteme": fetchAMO("firefox", "{6f54ad3f-042f-408f-8f06-ab631fe1a64f}"),
    "keepassxc-browser": fetchAMO("firefox", "keepassxc-browser@keepassxc.org"),
    "languagetool": fetchAMO("firefox", "languagetool-webextension@languagetool.org"),
    "libredirect": fetchAMO("firefox", "7esoorv3@alefvanoon.anonaddy.me"),
    "multi-account-containers": fetchAMO("firefox", "@testpilot-containers"),
    "noscript": fetchAMO("firefox", "{73a6fe31-595d-460b-a920-fcc0f8843232}"),
    "obsidian-web-clipper": fetchAMO("firefox", "clipper@obsidian.md"),
    "plasma-integration": fetchAMO("firefox", "plasma-browser-integration@kde.org"),
    "privacy-badger": fetchAMO("firefox", "jid1-MnnxcxisBPnSXQ@jetpack"),
    "privacy-pass": fetchAMO("firefox", "{48748554-4c01-49e8-94af-79662bf34d50}"),
    "react-devtools": fetchAMO("firefox", "@react-devtools"),
    "redux-devtools": fetchAMO("firefox", "extension@redux.devtools"),
    "return-youtube-dislike": fetchAMO("firefox", "{762f9885-5a13-4abd-9c77-433dcd38b8fd}"),
    "sidebery": fetchAMO("firefox", "{3c078156-979c-498b-8990-85f7987dd929}"),
    "snowflake": fetchAMO("firefox", "{b11bea1f-a888-4332-8d8a-cec2be7d24b9}"),
    "sponsorblock": fetchAMO("firefox", "sponsorBlocker@ajay.app"),
    "steamdb": fetchAMO("firefox", "firefox-extension@steamdb.info"),
    "stylus": fetchAMO("firefox", "{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}"),
    "svelte-devtools": fetchAMO("firefox", "{a0370179-acc3-452f-9530-246b6adb2768}"),
    "tampermonkey": fetchAMO("firefox", "firefox@tampermonkey.net"),
    "tree-style-tab": fetchAMO("firefox", "treestyletab@piro.sakura.ne.jp"),
    "tridactyl": fetchAMO("firefox", "tridactyl.vim@cmcaine.co.uk"),
    "tridactyl-beta": fetchMozilla("https://tridactyl.cmcaine.co.uk/betas/updates.json").pipe(addon("tridactyl.vim.betas@cmcaine.co.uk")),
    "ublock-origin": fetchAMO("firefox", "uBlock0@raymondhill.net"),
    "unhook": fetchAMO("firefox", "myallychou@gmail.com"),
    "user-agent-switcher": fetchAMO("firefox", "{a6c4a591-f1b2-4f03-b3ff-767e5bedf4e7}"),
    "video-download-helper": fetchAMO("firefox", "{b9db16a4-6edc-47ec-a1f4-b86292ed211d}"),
    "vimium": fetchAMO("firefox", "{d7742d87-e61d-4b78-b8a1-b469842139fa}"),
    "violentmonkey": fetchAMO("firefox", "{aecec67f-0d10-4fa7-b7c7-609a2db280cf}"),
    "vuejs-devtools": fetchAMO("firefox", "{5caff8cc-3d2e-4110-a88a-003cc85b3858}"),
    "web-archives": fetchAMO("firefox", "{d07ccf11-c0cd-4938-a265-2a4d6ad01189}"),
    "zotero-connector": fetchMozilla("https://www.zotero.org/download/connector/firefox/release/updates.json").pipe(addon("zotero@chnm.gmu.edu")),
  },
  thunderbird: {
    "cardbook": fetchAMO("thunderbird", "cardbook@vigneau.philippe"),
    "conversations": fetchAMO("thunderbird", "gconversation@xulforum.org"),
    "extract-em": fetchAMO("thunderbird", "extractem@tmccoid.tech"),
    "import-export-tools-ng": fetchAMO("thunderbird", "ImportExportToolsNG@cleidigh.kokkini.net"),
    "languagetool": fetchAMO("thunderbird", "languagetool-mailextension@languagetool.org"),
    "minimize-on-close": fetchAMO("thunderbird", "minimizeonclose@rsjtdrjgfuzkfg.com"),
    "quicktext": fetchAMO("thunderbird", "{8845e3b3-e8fb-40e2-95e9-ec40294818c4}"),
    "send-later": fetchAMO("thunderbird", "sendlater3@kamens.us"),
  },
  zotero: {
    "attachment-scanner": fetchGitHub({
      owner: "SciImage",
      repo: "zotero-attachment-scanner",
      id: "attachmentscanner@changlab.um.edu.mo",
    }),
    "better-bibtex": fetchGitHub({
      owner: "retorquere",
      repo: "zotero-better-bibtex",
      id: "better-bibtex@iris-advies.com",
    }),
    "folder-import": fetchGitHub({
      owner: "retorquere",
      repo: "zotero-folder-import",
      id: "folder-import@iris-advies.com",
    }),
    "ocr": fetchGitHub({
      owner: "UB-Mannheim",
      repo: "zotero-ocr",
      id: "zotero-ocr@bib.uni-mannheim.de",
    }),
    "open-pdf": fetchGitHub({
      owner: "retorquere",
      repo: "zotero-open-pdf",
      id: "open-pdf@iris-advies.com",
    }),
    "pmcid-fetcher": fetchGitHub({
      owner: "retorquere",
      repo: "zotero-pmcid-fetcher",
      id: "pmcid-fetcher@iris-advies.com",
    }),
    "pubpeer": fetchGitHub({
      owner: "PubPeerFoundation",
      repo: "pubpeer_zotero_plugin",
      id: "pubpeer@pubpeer.com",
    }),
    "scite": fetchGitHub({
      owner: "scitedotai",
      repo: "scite-zotero-plugin",
      id: "scite-zotero-plugin@scite.ai",
    }),
  },
};
