name: "Update addons"
on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    name: "Update addons"
    runs-on: ubuntu-slim

    permissions:
      contents: write

    steps:
      - uses: denoland/setup-deno@v2

      - uses: actions/checkout@v7
        with:
          path: master

      - uses: actions/checkout@v7
        with:
          ref: data
          path: data

      - name: "Update addons"
        working-directory: master
        run: deno run --frozen -A src/main.ts ../data

      - uses: EndBug/add-and-commit@v11
        with:
          cwd: data
          default_author: github_actions
